### PR TITLE
detect on image or filename

### PR DESCRIPTION
**Pull request by seanreynoldscs**
I would like the option to use predict without having to touch the disk.

### CODE REVIEW

**Comment by seanreynoldscs** [comment]
Is there anything still required for this? Its too late to see the welcome.yaml issue.

**Comment by capjamesg** [comment]
Thank you for your contribution! For some reason I wasn't getting notifications for individual `autodistill` repositories when we first created them. This PR relates to a broader question that we have not yet answered on data formats. I think we'd want to offer the image loading functionality in `autodistill` itself, rather than individual models. Then we would update each model to use the parent `autodistill` image loader. I will flag this with the team and see what we can do.

**Comment by seanreynoldscs** [comment]
Any update on this? If this functionality is available in a different way, I'm happy to change the way I'm using it.

**Comment by capjamesg** [comment]
@seanreynoldscs Thank you for your contribution! We have been working hard on support for loading images from memory and. We are excited to say that DETIC now has support for loading images from memory. You can pass in a PIL or cv2 array as the `input` argument, rather than a file name.

This is being rolled out to other Autodistill modules, too.

Let me know if you have any questions!

**Comment by capjamesg** [comment]
Note: You will need to run `pip install --upgrade autodistill autodistill-detic` to use the feature to load images from memory.

**Pull request closed without merging**
